[illumio]
fqdn = "<fqdn>"
port = 8443 # Integer (no quotes).
org = 1 # Integer (no quotes). Value is 1 for on-prem PCE installations.
user = "<api_id>"
key = "<api_key>"
match_field = "host_name" # Matches to ServniceNow match_field. Must either be "host_name" or "name".

[serviceNow]
table_url = "https://dev61812.service-now.com/cmdb_ci_server_list.do"
user =  "admin"
password = "U9%*#Mkf#8l7"
match_field = "host_name"

[labelMapping]
## To ignore a field (e.g., not sync the app field) comment the line.
app = "u_application"
enviornment = "used_for"
location = "u_data_center"
role = "u_type"

[logging]
log_only = false # True will make no changes to PCE. Log will reflect what will be updated if set to false.
log_directory = "" # Blank value stores log in same folder where tool is run.


### DO NOT USE THIS PIECE - KEEP SET TO FALSE ###
[unmanagedWorkloads]
enable = false 
table = "cmdb_ci_server_list" # "cmdb_ci_server_list.do" or "cmdb_ci_network_adapter"